SELECT CASE WHEN ST_Length(ST_GeomFromText('LINESTRING(0 0, 3 4)')) = 5.0 THEN 1 ELSE 0 END;
SELECT CASE WHEN ST_Area(ST_GeomFromText('POLYGON((0 0, 4 0, 4 4, 0 4, 0 0))')) = 16.0 THEN 1 ELSE 0 END;
SELECT CASE WHEN ST_Distance(ST_GeomFromText('POINT(0 0)'), ST_GeomFromText('POINT(3 4)')) = 5.0 THEN 1 ELSE 0 END;
SELECT CASE WHEN ST_X(ST_GeomFromText('POINT(7 11)')) = 7.0 THEN 1 ELSE 0 END;
SELECT CASE WHEN ST_Y(ST_GeomFromText('POINT(7 11)')) = 11.0 THEN 1 ELSE 0 END;
