SELECT CASE WHEN ST_AsText(CAST(NULL AS BLOB)) IS NULL THEN 1 ELSE 0 END;
SELECT CASE WHEN ST_Length(CAST(NULL AS BLOB)) IS NULL THEN 1 ELSE 0 END;
SELECT CASE WHEN ST_Distance(ST_GeomFromText('POINT(0 0)'), CAST(NULL AS BLOB)) IS NULL THEN 1 ELSE 0 END;
SELECT CASE WHEN ST_Buffer(CAST(NULL AS BLOB), 1.0) IS NULL THEN 1 ELSE 0 END;
SELECT CASE WHEN ST_Length(ST_GeomFromText('LINESTRING(0 0, 3 4)')) = 5.0 THEN 1 ELSE 0 END;
